name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    strategy:
      matrix:
        os:
          - alpine
          - centos
          - ubuntu
          - fedora

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3.1.0
      with:
        username: alexispeters
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Docker build amd
      run: docker buildx build  --platform linux/amd64 -f Dockerfile-${{ matrix.os }}-amd64 .
    - name: Docker build arm
      run: docker buildx build  --platform linux/arm64 -f Dockerfile-${{ matrix.os }}-arm64 .
    - name: Docker build i386
      run: docker buildx build  --platform linux/i386 -f Dockerfile-${{ matrix.os }}-i386 .

    - name: imagetools merge and push
      run: docker buildx imagetools create -t alexispeters/ansible:${{ matrix.os }}-$(date +%F) -t Dockerfile-${{ matrix.os }} Dockerfile-${{ matrix.os }}-i386 Dockerfile-${{ matrix.os }}-arm64 Dockerfile-${{ matrix.os }}-amd64

    - name: Push to ECR
      run: docker push alexispeters/ansible  -a
