name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3.1.0
      with:
        username: ${DOCKER_USERNAME}
        password: ${DOCKER_PASSWORD}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        file: Dockerfile
        tags: alexispeters/ansible:$(date +%s)+
        context: .
