name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3.1.0
      with:
        username: ${{ DOCKER_USERNAME }}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Docker build
      run: docker build . -f Dockerfile -t alexispeters/ansible:alpine-$(date +%F) -t alexispeters/ansible:alpine
    - name: Push to ECR
      run: docker push alexispeters/ansible
