name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    strategy:
      matrix:
        os:
          - alpine
          - centos
          - ubuntu
          - fedora

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3.1.0
      with:
        username: alexispeters
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Docker build
      run: docker build . -f Dockerfile-${{ matrix.os }} --platform linux/amd64,linux/arm64,linux/i386 -t alexispeters/ansible:${{ matrix.os }} $(date +%F) -t alexispeters/ansible:${{ matrix.os }}
    - name: Push to ECR
      run: docker push alexispeters/ansible  -a
