name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    strategy:
      matrix:
        os:
          - alpine
          - ubuntu
          - fedora
        platform:
          - arm64
          - amd64
          - arm/v7
          - arm/v8

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3.1.0
        with:
          username: alexispeters
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Docker build and push ${{ matrix.os }}-${{ matrix.platform }}
        run:  PLATFORM="${{matrix.platform}}" && export TAG_NAME="${PLATFORM/\//-}"  && docker buildx build --push  --platform linux/${{ matrix.platform }} -f Dockerfile-${{ matrix.os }} -t alexispeters/ansible:${{ matrix.os }}-${TAG_NAME} -t alexispeters/ansible:${{ matrix.os }}-${TAG_NAME}-$(date +%F)  .

  merge:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - alpine
          - ubuntu
          - fedora
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3.1.0
        with:
          username: alexispeters
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: docker pull 
        run: docker image pull --all-tags alexispeters/ansible
      - name: imagetools merge and push
        run: docker buildx imagetools create -t alexispeters/ansible:${{ matrix.os }}-$(date +%F) -t alexispeters/ansible:${{ matrix.os }} \
          docker.io/alexispeters/ansible:${{ matrix.os }}-arm64 docker.io/alexispeters/ansible:${{ matrix.os }}-amd64 
